
version: '3'
services:
  app:
    build: .
    container_name: app
    env_file: .env
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 3000:3000
    tty: true
    links:
      - mysql
  mysql:
    env_file:
     - .env
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql: